### ISSUE TITLE
Metamask send token failure

### ISSUE THREAD

**Issue by shunjizhan** [AcalaNetwork/bodhi.js#102]
when using the test account from here with metamask, https://github.com/AcalaNetwork/Acala/blob/66b83277f203b1515fac7cdfa2db4da8d8cfb6e0/node/service/src/chain_spec/mandala.rs#L77-L80, sending token will fail due with this error:

```
request error
    methodName: "eth_sendRawTransaction"
    params: [
      "0x02f87482053980843b9aca008477359400825728940085560b24769dac4ed057f1b2ae40746aa9aab6888ac7230489e8000080c080a0158ba84828b01dfaf67b5a2e17360346316ccb12f4fcebfa459178ce4be41915a05a63dae5dfc9e32618405fd7ef60a2d11e19251e641cfcd517aca14473c09f4d"
    ]
    err: {
      "type": "Error",
      "message": "1010: Invalid Transaction: Transaction is outdated",
      ...
    }
```

**Comment by zjb0807** [comment]
Have you changed the gasPrice?
```
gasPrice: 429496729610000, // storage_limit = 100000, validUntil = 10000, 100000 << 32 | 10000
```

**Comment by xlc** [comment]
We can’t really support the default send token feature without asking user to enter some seemingly ridiculous gas price (and tx fee) so it is just a won’t support thing.

**Comment by shunjizhan** [comment]
does it mean user have to manually enter a super high gas price every time they send transaction through metamask? In this way metamask will block user from sending, saying insufficient fund (due to super high estimation of transaction fee)
<img width="351" alt="Screen Shot 2021-11-10 at 19 53 55" src="https://user-images.githubusercontent.com/16548786/141108773-abe1a8ef-732c-45f2-a541-46644025f01d.png">

**Comment by shunjizhan** [comment]
@ianhe8x

**Comment by xlc** [comment]
Yeah so it is just something we cannot support.
The recommended way will be perform token transfer in our (to-be-built) dApp.

**Comment by shunjizhan** [comment]
close it since it is not a bug then

**Comment by ianhe8x** [comment]
> We can’t really support the default send token feature without asking user to enter some seemingly ridiculous gas price (and tx fee) so it is just a won’t support thing. 

So is it an issue only when send native token and won't be same case for contract calls?

**Comment by xlc** [comment]
The issue exists if the transaction is created by Metamask. If the transaction is created by dApp that understand Acala EVM then it will be all good.

**Comment by ianhe8x** [comment]
what's the difference? does the dapp just need to suggest a proper gas price?

**Comment by xlc** [comment]
It should ask for EIP-712 signature instead of the standard Ethereum signature
