### ISSUE TITLE
Errors on RPC service 2.7.6

### ISSUE THREAD

**Issue by TurtleSnail** [AcalaNetwork/bodhi.js#1049]
I am running:
```
SUBQL_URL=http://localhost:3001 ENDPOINT_URL=ws://localhost:30510 PORT=30526 MAX_CACHE_SIZE=2000 SAFE_MODE=1 LOCAL_MODE=0 npx @acala-network/eth-rpc-adapter@2.7.6
```
It starts ok, and does return data when queried, however, I see these erros in the log, and I wonder if it is a problem?
```
Nov 09 08:33:42 ct12 bash[2159465]: 2024-11-09 08:33:42             VEC: Unable to decode on index 2 createType(ExtrinsicV4):: createType(Call):: findMetaCall: Unable to find Call with index [0, 70]/[0,70]
Nov 09 08:33:42 ct12 bash[2159465]: 2024-11-09 08:33:42        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: findMetaCall: Unable to find Call with index [0, 70]/[0,70]

```

**Comment by shunjizhan** [comment]
Hi, please use latest version `@acala-network/eth-rpc-adapter@2.9.1`, the errors should go away

**Comment by shunjizhan** [comment]
@TurtleSnail Hey dude, were you able to sign vaa for [this tx](https://wormholescan.io/#/tx/0xf6d121c1be1f06490c319b7056bdd84dba4739363368a00bdfcb058c323d6644?network=MAINNET) after upgrading? If not, what error/issue did you see? Thanks

**Comment by shunjizhan** [comment]
thanks for the info. If the subquery has finished indexing to the latest height, should be able to find the tx.

Could you please try calling this against eth rpc endpoint, an see if tx can be found?
```
curl --location <eth-rpc-url> \
--header 'Content-Type: application/json' \
--data '{
  "id": 0,
  "jsonrpc": "2.0",
  "method": "eth_getTransactionReceipt",
  "params": ["0xf6d121c1be1f06490c319b7056bdd84dba4739363368a00bdfcb058c323d6644"]
}'
```

**Comment by shunjizhan** [comment]
cool it seems eth rpc is returning the correct result. Can you advise what else are we missing to observe that tx and sign the vaa for it?

**Comment by shunjizhan** [comment]
Thanks! Are you in charge of any guardian service? I remember there is a `re-observe` task that can be run by the guardian service, were you able to try it out for this tx? 

According to my understanding, as long as the eth rpc can correctly return the tx, guardian service should be able to (re)observe it and emit vaa.

If you don't have access to to the guardian stuff, we will contact them to find out
