### ISSUE TITLE
sendRawTransaction needs support EIP-712 format transaction

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/bodhi.js#118]
https://github.com/AcalaNetwork/bodhi.js/blob/8db626315a6c7a3ab698b88b59e8a9f234e149cc/eth-providers/src/base-provider.ts#L537

It needs to support transaction signed with EIP-712 format

https://github.com/AcalaNetwork/Acala/blob/master/ts-tests/tests/test-sign-eip712.ts

**Comment by ntduan** [comment]
TransactionType 0x60
TransactionPayload rlp([chainId, nonce, gasPrice, to, value, data, eip712sig])

**Comment by ntduan** [comment]
example: https://github.com/AcalaNetwork/bodhi.js/blob/master/eth-providers/src/__tests__/e2e/tx.test.ts#L87-L106
