### ISSUE TITLE
`eth_getBlockByNumber` issue causing errors and multiple retries

### ISSUE THREAD

**Issue by gluneau** [AcalaNetwork/bodhi.js#157]
It seems that a request come for eth_getBlockByNumber with a param of latest, we can see that the block number is 8, then the next request for eth_getBlockByNumber with a param of 9! it errors out because this block does not yet exist.  Is there an increment error here or another yet to be parsed block?

![image](https://user-images.githubusercontent.com/2903505/144125954-ea20c192-73f8-4821-9d2a-12022bc2dd0f.png)

Truffle comments on running tests:
![image](https://user-images.githubusercontent.com/2903505/144126073-e7383d76-8a29-4ae2-b081-5163ef851dee.png)
 ```
 2) Contract: Test
       "after each" hook: after test for "Invalid token amounts":
     blocktag should be number | 'latest' | 'earliest' (argument="blockTag", value="0x6d", code=INVALID_ARGUMENT, version=bodhi.js/providers/2.1.4)
``` 

A count of this error found in running a test suite occurs more than 2700 times.

**Comment by gluneau** [comment]
Under WH project, I'm still getting this error 30970 times. 


```
[1638318896612] DEBUG (1780071 on XPS-15-7590): incoming request
    id: 36100
    jsonrpc: "2.0"
    params: [
      "0x22a",
      false
    ]
    method: "eth_getBlockByNumber"
[1638318896613] ERROR (1780071 on XPS-15-7590): request error
    methodName: "eth_getBlockByNumber"
    params: [
      "0x22a",
      false
    ]
    err: {
      "type": "Error",
      "message": "Unable to retrieve header and parent from supplied hash",
      "stack":
          Error: Unable to retrieve header and parent from supplied hash
              at assert (/home/bodhi.js/common/temp/node_modules/.pnpm/@polkadot+util@7.9.2/node_modules/@polkadot/util/assert.cjs:36:11)
              at ApiPromise._getBlockRegistry (/home/bodhi.js/common/temp/node_modules/.pnpm/@polkadot+api@6.9.2/node_modules/@polkadot/api/base/Init.cjs:227:22)
              at processTicksAndRejections (internal/process/task_queues.js:95:5)
    }
[1638318896613] DEBUG (1780071 on XPS-15-7590): request completed
    id: 36100
    jsonrpc: "2.0"
    error: {
      "code": 6969,
      "message": "Error: Unable to retrieve header and parent from supplied hash"
    }
```

**Comment by ntduan** [comment]
> Under WH project, I'm still getting this error 30970 times.
> 
> ```
> [1638318896612] DEBUG (1780071 on XPS-15-7590): incoming request
>     id: 36100
>     jsonrpc: "2.0"
>     params: [
>       "0x22a",
>       false
>     ]
>     method: "eth_getBlockByNumber"
> [1638318896613] ERROR (1780071 on XPS-15-7590): request error
>     methodName: "eth_getBlockByNumber"
>     params: [
>       "0x22a",
>       false
>     ]
>     err: {
>       "type": "Error",
>       "message": "Unable to retrieve header and parent from supplied hash",
>       "stack":
>           Error: Unable to retrieve header and parent from supplied hash
>               at assert (/home/bodhi.js/common/temp/node_modules/.pnpm/@polkadot+util@7.9.2/node_modules/@polkadot/util/assert.cjs:36:11)
>               at ApiPromise._getBlockRegistry (/home/bodhi.js/common/temp/node_modules/.pnpm/@polkadot+api@6.9.2/node_modules/@polkadot/api/base/Init.cjs:227:22)
>               at processTicksAndRejections (internal/process/task_queues.js:95:5)
>     }
> [1638318896613] DEBUG (1780071 on XPS-15-7590): request completed
>     id: 36100
>     jsonrpc: "2.0"
>     error: {
>       "code": 6969,
>       "message": "Error: Unable to retrieve header and parent from supplied hash"
>     }
> ```

How to reproduce？

**Comment by shunjizhan** [comment]
WH project is this one https://github.com/certusone/wormhole/tree/dev.v2/ethereum

**Comment by shunjizhan** [comment]
after `yarn` we need to add mandala network settings like here https://github.com/AcalaNetwork/bodhi.js/blob/master/examples/truffle/truffle-config.js

then
`yarn migrate --network mandala`

**Comment by gluneau** [comment]
Also for wormhole, you'll need to run this at least once after running `truffle compile`
`mkdir -p build/contracts && cp node_modules/@openzeppelin/contracts/build/contracts/* build/contracts/`

**Comment by ntduan** [comment]
![image](https://user-images.githubusercontent.com/7029338/149235808-2b5e62ed-b345-44f8-8290-a610f0916a7a.png)
The test cases for the wormhole contract all pass with the latest code (set to 1 second per block).
