### ISSUE TITLE
Struct: failed on gas_limit, Negative number passed to unsigned type

### ISSUE THREAD

**Issue by gluneau** [AcalaNetwork/bodhi.js#187]
Replicate by following this [Tutorial](https://wiki.acala.network/build/development-guide/smart-contracts/get-started-evm/use-hardhat)

And using this networks parameter:
```
networks: {
    mandala: {
      url: 'https://tc7-eth.aca-dev.network',
      chainId: 595,
      gasPrice: 200786445289,
      gas: 34132001,
      timeoutBlocks: 25,
      confirmations: 0,
      // Development built-in default deployment account
      accounts: ["0xa872f6cbd25a0e04a08b1e21098017a9e6194d101d75e13111f71410c59cd57f"]
    }
  }
```

`yarn hardhat run scripts/sample-script.js --network mandala`

Log:
```
yarn run v1.22.5
warning package.json: No license field
$ node_modules/.bin/hardhat run scripts/sample-script.js --network mandala
ProviderError: Error: createType(Call):: Call: failed decoding evm.ethCall:: Struct: failed on args: {"action":"{\"_enum\":{\"Call\":\"H160\",\"Create\":\"Null\"}}","input":"Bytes","value":"Compact<u128>","gas_limit":"Compact<u64>","storage_limit":"Compact<u32>","valid_until":"Compact<u32>"}:: Struct: failed on gas_limit: Compact<u64>:: u64: Negative number passed to unsigned type
    at HttpProvider.request (node_modules/hardhat/src/internal/core/providers/http.ts:49:19)
    at LocalAccountsProvider.request (node_modules/hardhat/src/internal/core/providers/accounts.ts:181:36)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ntduan** [comment]
![image](https://user-images.githubusercontent.com/7029338/146108769-83c60e11-00cd-41a5-9442-bb81c71094fd.png)
hardhat does not support this setup. You need to manually override gaslimit and gasprise each time call the contract.
```
constrat.call(....., {
  gasLimit: ...,
  gasPrice: ...
 })
```

**Comment by gluneau** [comment]
Like this: 

```  networks: {
    mandala: {
      url: 'https://tc7-eth.aca-dev.network',
      chainId: 595,
      // Development built-in default deployment account
      accounts: ["0xa872f6cbd25a0e04a08b1e21098017a9e6194d101d75e13111f71410c59cd57f"]
    }
  }
```

`sample-script.js`
```
  const greeter = await Greeter.deploy("Hello, Hardhat!", {
    gasLimit: 200786445289,
    gasPrice: 34132001
  });
```
  
Log:  
```
```

**Comment by shunjizhan** [comment]
maybe this will work? :joy:
https://github.com/AcalaNetwork/worm_hole/commit/c6a3bf2a1843b9b681e445843a726600cde9b8c2#diff-ea0e60faa0d8da36cbeef86ad16e3d33df4c0094ec8959a9832e3f3debcdb9faR33-R43

**Comment by shunjizhan** [comment]
Is there a more deterministic way to figure out a working gas price?

**Comment by ntduan** [comment]
https://github.com/AcalaNetwork/bodhi.js/blob/master/examples/hardhat/test/HelloWorld.test.ts#L10-L16

You must use this function to get gasLimit and gasPrice.

**Comment by ntduan** [comment]
https://github.com/AcalaNetwork/bodhi.js/pull/192/files 

I have improved the error message. When your gaslimit or gasPrice are errors, it will print out what they are.

**Comment by ntduan** [comment]
> Like this:
> 
> ```
>     mandala: {
>       url: 'https://tc7-eth.aca-dev.network',
>       chainId: 595,
>       // Development built-in default deployment account
>       accounts: ["0xa872f6cbd25a0e04a08b1e21098017a9e6194d101d75e13111f71410c59cd57f"]
>     }
>   }
> ```
> 
> `sample-script.js`
> 
> ```
>   const greeter = await Greeter.deploy("Hello, Hardhat!", {
>     gasLimit: 200786445289,
>     gasPrice: 34132001
>   });
> ```
> 
> Log:
> 
> ```
> ➜  hardhat3 yarn hardhat run scripts/sample-script.js --network mandala
> yarn run v1.22.5
> warning package.json: No license field
> $ node_modules/.bin/hardhat run scripts/sample-script.js --network mandala
> ProviderError: Error: cannot shift negative values (fault="cannot shift negative values", operation="shr", code=NUMERIC_FAULT, version=bignumber/5.4.2)
>     at HttpProvider.request (node_modules/hardhat/src/internal/core/providers/http.ts:49:19)
>     at LocalAccountsProvider.request (node_modules/hardhat/src/internal/core/providers/accounts.ts:181:36)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
>     at EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
> error Command failed with exit code 1.
> ```

In this case, just exchange gasPrice and gasLimit. 
```
>   const greeter = await Greeter.deploy("Hello, Hardhat!", {
>     gasLimit: 200786445289 -> 34132001,
>     gasPrice: 34132001 -> 200786445289
>   });
```
