### ISSUE TITLE
Metamask Precision 

### ISSUE THREAD

**Issue by shunjizhan** [AcalaNetwork/bodhi.js#194]
metamask uses 18 digits and mandala supports 12 digits, so if user input `0.{16}1`, this will be truncated to `0.{12}1000000`

**Comment by zjb0807** [comment]
After the MetaMask is supported, verify and check the amount ends in `000000`

**Comment by zjb0807** [comment]
![image](https://user-images.githubusercontent.com/16496415/148021871-626daefc-1426-420b-9213-84e31fb93494.png)

The maximum precision currently supported is 8 bits, so there is no impact
