### ISSUE TITLE
Error: while migrating Migrations: EIP-1559 transactions not implemented 

### ISSUE THREAD

**Issue by gluneau** [AcalaNetwork/bodhi.js#201]
Not providing: 
```
  gasPrice: 200786445289,
  gas: 42032000,
```
while running the default truffle example causes this error: 

`Error: while migrating Migrations: EIP-1559 transactions not implemented (method="EIP-1559 transactions", provider="eth-providers", code=NOT_IMPLEMENTED, version=bodhi.js/providers/2.1.7)`

**Comment by ntduan** [comment]
We still don't support eip1559 format, right? @xlc

**Comment by ntduan** [comment]
The default is eip1559 transaction, but this should be settable, just set the type to 0 or 1

**Comment by gluneau** [comment]
https://github.com/AcalaNetwork/Acala/pull/1709
