### ISSUE TITLE
CI Remove Loop Container

### ISSUE THREAD

**Issue by shunjizhan** [AcalaNetwork/bodhi.js#212]
when running hardhat test, if loop.js is in the test folder, it should run along with other tests automatically, so we don't need to run it in a separate container. This should save some building time

**Comment by ThunderDeliverer** [comment]
This is already the case. If you invoke tests everything in the test folder is run. The loop.js helper was removed from all of the networks except the CI network, so I think we can close this issue (or maybe wait until the reference to Hardhat tutorials is updated in bodhi.js and close it then). 🤔

**Comment by shunjizhan** [comment]
I mean in CI tests we still run loop separately as a service https://github.com/AcalaNetwork/bodhi.js/blob/master/docker-compose.yml#L136

After we merge new examples structure, we won't need this anymore since as you mentioned, everything in the test folder including loop should run
