### ISSUE TITLE
RPC adaptor production log not showing details

### ISSUE THREAD

**Issue by shunjizhan** [AcalaNetwork/bodhi.js#228]
currently we couldn't see the request and responds details

<img width="713" alt="Screen Shot 2022-01-13 at 09 43 59" src="https://user-images.githubusercontent.com/16548786/149250820-e4cc411f-7a9c-427a-94e8-21a01a233630.png">
 
in order to better investigate any issue with production, we should make it logs all request/response details, just like in local dev

**Comment by ntduan** [comment]
I think it's not that there is no request information and it' s because these requests just don't have request information.

like this: 

`curl https://tc7-eth.aca-dev.network`
![image](https://user-images.githubusercontent.com/7029338/149255361-0df88fa6-7784-4f12-9a45-3ecfab065f63.png)

**Comment by ntduan** [comment]
![image](https://user-images.githubusercontent.com/7029338/149256048-2efe67e8-862f-40a2-a88f-aaf3d099513b.png)
![image](https://user-images.githubusercontent.com/7029338/149256085-ee0e857e-3f3b-4fc7-8fcc-2c44452d17cd.png)
This is a normal request

**Comment by ntduan** [comment]
![image](https://user-images.githubusercontent.com/7029338/149256315-27119bdd-173a-4db9-a58b-8afdedc11710.png)
Normal requests are having details. I don't know where these error requests are coming from. Maybe it's just some crawler bots.

**Comment by shunjizhan** [comment]
ahh you are right, valid ones actually have these details. It's just so hard to find it among so many bot requests :sweat_smile:
