### ISSUE TITLE
Metamask cannot cancel or speed up a transaction.

### ISSUE THREAD

**Issue by ntduan** [AcalaNetwork/bodhi.js#230]
![image](https://user-images.githubusercontent.com/7029338/149436881-327b8547-e439-4332-a5f9-476878ecc6fe.png)

and will resend the transaction in an infinite loop. Even restarting the browser does not prevent it.

**Comment by ntduan** [comment]
> That will means sign a transaction with different gas price, which isn't what we can support at this stage.

But in any case, we need a way to cancel the transaction. Currently there is no way to cancel the transaction other than deleting the account.

**Comment by shunjizhan** [comment]
yeah I also seen this situation before, but I think this is caused by when using `instant-sealing`, after metamask send a tx, this tx isn't included in a new block, and node didn't trigger a new block either... 

metmask keeps searching for this non-exist tx hash, and ignores following ones

**Comment by shunjizhan** [comment]
we can go to metamask settings => advanced => reset account to clear metamask cache

**Comment by shunjizhan** [comment]
I can do more experiment to see how to reproduce this issue deterministically, I have seen this very rarely and randomly

**Comment by shunjizhan** [comment]
UPDATE: got it, when first time sending token to a *brand new account*, it won't trigger a new block, but the tx actually went through and succeed.

**Comment by shunjizhan** [comment]
I think I know what's happening: **we have to clear metamask cache every time we restart mandala node**... otherwise there will be some nonce issue, i.e. metamask will use cached tx to speculate currently nonce...
