### ISSUE TITLE
Hardhat deployment transaction gas & storage fee calculation are too small

### ISSUE THREAD

**Issue by gluneau** [AcalaNetwork/bodhi.js#240]
Need to find a way to have hardhat get the proper deployment transaction gas & storage fee calculation so that we don't need to implement code modification specific to Acala.

![image](https://user-images.githubusercontent.com/2903505/149851843-3fb5ca80-0b6c-4b5b-9936-6ac1ea5e0912.png)

**Comment by ntduan** [comment]
https://github.com/ethers-io/ethers.js/discussions/2443 

I have raised this issue to ethers before, but still no solutions.
