### ISSUE TITLE
Balance is different

### ISSUE THREAD

**Issue by zjb0807** [AcalaNetwork/bodhi.js#251]
![image](https://user-images.githubusercontent.com/16496415/151119505-8818c76b-862a-4458-8520-7538b3a65994.png)

First is native, second is ACA erc20. import `0x0000000000000000000100000000000000000000 `

**Comment by shunjizhan** [comment]
I think first one is showing free balance, second one is showing all balance. Is first one the expected behavior? 

second balance is returned by `eth_call` to ACA contract directly, so probably we should change the underlying behavior of `eth_call` to return free balance?

**Comment by shunjizhan** [comment]
```
eth_call {
  to: '0x0000000000000000000100000000000000000000',
  data: 'balance of xxx'
}
```

**Comment by zjb0807** [comment]
https://github.com/AcalaNetwork/Acala/blob/master/modules/evm/src/lib.rs#L1283

It's `free_balance`. But will change to `reducible_balance`.
https://github.com/AcalaNetwork/Acala/issues/1343

Should check the first balance and use the `reducible_balance`

**Comment by zjb0807** [comment]
https://github.com/AcalaNetwork/bodhi.js/blob/f1c93005523e3d3a67fc3164e8f153fe2d82dabe/eth-providers/src/base-provider.ts#L465-L467

**Comment by zjb0807** [comment]
https://github.com/paritytech/substrate/blob/master/frame/balances/src/lib.rs#L1075-L1088
