### ISSUE TITLE
optimize getTXByHash 

### ISSUE THREAD

**Issue by shunjizhan** [AcalaNetwork/bodhi.js#290]
currently we will retry 20 times, because we need to wait for next block to be able to find it, in this case we will need to wait 20 seconds if tx is not found.

Can think about ways to optimize this, maybe we can cache those "sent but not mined TX" in rpc-adaptor

**Comment by xlc** [comment]
you can check the tx pool to see if it is there or not and if is not in txpool nor recently mined block, it is not there

**Comment by shunjizhan** [comment]
that sounds like a good idea, by saying txpool do you mean pending extrinsics?

**Comment by xlc** [comment]
yes
