### ISSUE TITLE
Tests for Mandala Health

### ISSUE THREAD

**Issue by shunjizhan** [AcalaNetwork/bodhi.js#294]
Currently in order to answer the question "is mandala healthy", it takes 10min to do some manual testing/inspecting, we can write some tests to automate this process, so it will take 1 command line run to check mandala health.
- **indexer** (most important, other things never failed so far if this is healthy):`net_indexer()`
  - compare `lastProcessedHeight`, `targetHeight` with current block height
  - compare `lastProcessedTimestamp` to current time.
- graphql: make graphql query to `https://tc7-graphql.aca-dev.network` directly, check if:
  - earliest txReceipt and logs exist.
  - middle txReceipt and logs exist.
  - latest txReceipt and logs exist.
- rpc: make some example calls: 
  - `net_cacheInfo` and check `cachedBlocks` and latest block
  - `eth_getLogs` (earliest, middle, latest logs)
  - `eth_getTxByHash`, `eth_getTxReceipt` (earliest, middle, latest txs)
  - `eth_call`
  - `eth_getCode`

A better version will be some sort of UI that integrates these checks, which keeps checking indexer every 10 min, checks graph and rpc every hour, and display the result/error. Maybe have a button to manually re-run the checks.

**Comment by shunjizhan** [comment]
related to #249

**Comment by xlc** [comment]
we can have a health check endpoint and configure datadog to call the endpoint every 10 mins. we could setup alerts and see historical results from datadog.

**Comment by shunjizhan** [comment]
sounds good, we can prioritize #249 over this one. For the health check endpoint, I think checking indexer health should be enough, since as along as indexer is healthy, other services work as expected (so far). If in the future we found other services failed while indexer is healthy, we can then make some other tests to cover it.

**Comment by shunjizhan** [comment]
already have health monitoring endpoint with datadog
