### ISSUE TITLE
Precompiled tokens like DOT, LDOT, KSM, LKSM or aUSD do not show balances in metamask except for ACA

### ISSUE THREAD

**Issue by gluneau** [AcalaNetwork/bodhi.js#303]
Having connected to AcalaMandalaTC7 on my MetaMask I can see my ACA balance as it also shows here https://apps.mandala.acala.network/portfolio

Using https://github.com/AcalaNetwork/predeploy-contracts/blob/master/contracts/utils/Address.sol
I try to then import tokens in my MetaMask, but they are no longer recognised by MetaMask.

So importing precompiled no longer works:
![image](https://user-images.githubusercontent.com/2903505/157350557-52faa187-3930-44b5-a944-10cc7172075c.png)

Metamask assets with 0 balances:
![image](https://user-images.githubusercontent.com/2903505/157349593-c79060a3-418e-4dc2-b16f-0310055ba141.png)

Apps website with correct balances:
![image](https://user-images.githubusercontent.com/2903505/157349807-c4cac296-4eb0-471d-8dac-8d0e82e73fa3.png)

**Comment by Yuxanju** [comment]
You will need to synchronize your wallet and then you debug it

**Comment by gluneau** [comment]
Will re-test once this issue is fixed:  https://github.com/AcalaNetwork/Acala/issues/1947

**Comment by Yuxanju** [comment]
You will need to synchronize your wallet and then you debug it

**Comment by gluneau** [comment]
Balance now shows, tokens are capable of being added again.
Issue resolved.
