### ISSUE TITLE
Improved concurrency performance

### ISSUE THREAD

**Issue by ntduan** [AcalaNetwork/bodhi.js#332]
https://github.com/polkadot-js/api/issues/4707

**Comment by shunjizhan** [comment]
I think we can also do some caching for `apiAt` for the latest 10 blocks, since most queries ask for these blocks. The implementation should be pretty similar to how we cache tx hashes

**Comment by shunjizhan** [comment]
so basically if many request comes in, they can share the same instance of `apiAt` and won't need to make many new connections. But still, this is a workaround we can do, it will definitely be nice to improve concurrency performance from the api itself

**Comment by ntduan** [comment]
> I think we can also do some caching for `apiAt` for the latest 10 blocks in RPC adaptor, since most queries ask for these blocks. The implementation should be pretty similar to how we cache tx hashes

Yes, the api has fixed some of the problems. But it still creates a new api object for each blockhash, which can cause a lot of memory consumption and service crash when processing many requests at the same time. I will create a block registry based cache.
