### ISSUE TITLE
[Wormhole] Cannot redeem NFTs in Karura-dev

### ISSUE THREAD

**Issue by timbrinded** [AcalaNetwork/bodhi.js#364]
## Description
When bridging a NFT from ForeignChain -> Karura; the final step for redemption errors and does not function.

## Steps to recreate
1. On BSC/Matic etc bridge a NFT to Karura
2. wait for bridge to complete
3. Click redeem

![cannotRedeem](https://user-images.githubusercontent.com/79199034/162949699-057e607e-d696-4eae-bed8-11b6dbc6da88.gif)

> Metamask throws error to console and no transaction is constructed to verify and submit:
```
code: -32603
data: {code: 6969, message: 'Error: -32603: VM Exception while processing transaction: execution revert invalid emitter: 0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000f696e76616c696420656d69747465720000000000000000000000000000000000"'}
message: "Internal JSON-RPC error."
```

N.B. @zjb0807  believes this is a wormhole error, so may be worth chasing up with them

**Comment by zjb0807** [comment]
https://blockscout.karura-dev.aca-dev.network/token/0xaafdf08b2721e57792526cdb9fa198791b4f85a8/instance/888886/token-transfers

works now
