### ISSUE TITLE
ProviderError: Error: -32603: execution error: OutOfOffset: 0x

### ISSUE THREAD

**Issue by gluneau** [AcalaNetwork/bodhi.js#366]
ProviderError: Error: -32603: execution error: OutOfOffset: 0x
specifically,  trying to run this command:
```
cd packages/contracts
hardhat test test/contracts/token/Vesting.ts --network mandala
```

**Comment by zjb0807** [comment]
```
{
    "jsonrpc": "2.0",
    "method": "eth_estimateGas",
    "params": [
        {
            "data": "0xb6b55f250000000000000000000000000000000000000000000000000000000000989680",
            "from": "0xd2a5c8867d1b3665fb3b2d93d514bd1c73bb2227",
            "to": "0x4e3e1108e86c3fafb389629e99bff9c4fa911e54"
        }
    ],
    "id": 1
}
```
I find the RPC returns the error.

`0xb6b55f25` is signature of `deposit(uint256)`.  
Can you check the contract at `0x4e3e1108e86c3fafb389629e99bff9c4fa911e54` with `deposit(uint256)`?

**Comment by zjb0807** [comment]
https://github.com/rust-blockchain/evm/pull/94/files#diff-363a23d98a6c2addecef2665cf68deec178a1dc19d7b625439d4cc50f7f4af50R140

In `eth_estimateGas` RPC, `OutOfGas` should be returned, but because the index has changed, the client thinks it is `OutOfOffset`.
Upgrading the client is resolved
