### ISSUE TITLE
BigNumber types are different

### ISSUE THREAD

**Issue by zjb0807** [AcalaNetwork/bodhi.js#388]
```
import { BigNumber } from '@ethersproject/bignumber';
import { BigNumber as BigNumberNew } from "ethers";

console.log(BigNumber.from("1") === BigNumberNew.from("1"))
```

**Comment by zjb0807** [comment]
@ntduan Should we import all from ethers instead of ethersproject?

**Comment by zjb0807** [comment]
https://github.com/AcalaNetwork/bodhi.js/blob/dc018192ebdd7e96655a332fd234406a86831dd7/bodhi/package.json#L17-L25

**Comment by ntduan** [comment]
I think it will be solved after this pr(https://github.com/AcalaNetwork/bodhi.js/pull/386) merge.

**Comment by zjb0807** [comment]
```
{
        "name": "ts-tests",
        "version": "1.0.0",
        "main": "index.js",
        "license": "GPL-3.0-or-later",
        "scripts": {
                "test": "export NODE_ENV=test && mocha -r ts-node/register/transpile-only --timeout 50000 --no-warnings tests/**/test-*.{js,ts}",
                "build": "waffle waffle.json",
                "run-test": "yarn mocha -r ts-node/register/transpile-only --timeout 50000 --no-warnings"
        },
        "dependencies": {
                "@acala-network/bodhi": "^2.4.6",
                "@openzeppelin/contracts": "4.4.2",
                "@types/chai": "^4.2.22",
                "@types/chai-as-promised": "^7.1.4",
                "@types/mocha": "^9.0.0",
                "chai": "^4.3.4",
                "chai-as-promised": "^7.1.1",
                "ethereum-waffle": "3.4.0",
                "ethers": "~5.6.4",
                "mocha": "^9.1.3",
                "mocha-steps": "^1.3.0",
                "ts-node": "^10.7.0",
                "typescript": "^4.6.3",
                "get-port": "^5.1.1"
        }
}
```

**Comment by ntduan** [comment]
> ```
> {
>         "name": "ts-tests",
>         "version": "1.0.0",
>         "main": "index.js",
>         "license": "GPL-3.0-or-later",
>         "scripts": {
>                 "test": "export NODE_ENV=test && mocha -r ts-node/register/transpile-only --timeout 50000 --no-warnings tests/**/test-*.{js,ts}",
>                 "build": "waffle waffle.json",
>                 "run-test": "yarn mocha -r ts-node/register/transpile-only --timeout 50000 --no-warnings"
>         },
>         "dependencies": {
>                 "@acala-network/bodhi": "^2.4.6",
>                 "@openzeppelin/contracts": "4.4.2",
>                 "@types/chai": "^4.2.22",
>                 "@types/chai-as-promised": "^7.1.4",
>                 "@types/mocha": "^9.0.0",
>                 "chai": "^4.3.4",
>                 "chai-as-promised": "^7.1.1",
>                 "ethereum-waffle": "3.4.0",
>                 "ethers": "~5.6.4",
>                 "mocha": "^9.1.3",
>                 "mocha-steps": "^1.3.0",
>                 "ts-node": "^10.7.0",
>                 "typescript": "^4.6.3",
>                 "get-port": "^5.1.1"
>         }
> }
> ```

You need to specify `@ethersproject/bignumber: ~5.6.0` in package.json to ensure version consistency.

If you use rush, it will require all imported packages to be defined in package.json.

**Comment by ntduan** [comment]
The version of ethers used by bodhi.js is 5.5.0 . If you want to be consistent with the bignumber version of bodhi.js, then you should specify `@ethersproject/bignumber: ~5.5.0`

**Comment by zjb0807** [comment]
`@ethersproject` and `ethers` need to keep the version consistent in the future
