### ISSUE TITLE
Update Docs

### ISSUE THREAD

**Issue by shunjizhan** [AcalaNetwork/bodhi.js#397]
- [x] fix outdated info
- [ ] gas doc polish: for contract call, sometimes need custom gas (when), sometimes don't
- [x] for instant sealing nodes (such as following the doc node setup), it's normal to see indexer errors at the beginning when there is no tx
- [x] when fetching gas params in the frontend, not recommended to import provider (since this introduced extra dependecy, and we also haven't fully tested/documented using provider/bodhi in the browser env), recommended to use RPC call [example](https://github.com/certusone/wormhole/blob/dev.v2/bridge_ui/src/utils/karura.ts#L3)
- faq
  - [x] if tx stuck at metamask locally, may need to clear metamask cache, this usually happens when... (TODO)
  - [x] error: tx hash mismatch using `ethers.jsonRPCprovider`, need to use our own provider https://github.com/AcalaNetwork/wormhole-relayer/blob/master/src/relay/utils.ts#L95-L98
    - if see txid different than eth txid: yes, can't predict txid right now, hash in receipt is the real txhash 
  - [x] gas issue: just read doc
  - [x] how to know if a tx is finalized?
    - wait x block
    - use eth_isTXFinalized endpoint
    - use safe mode rpc (not publicly available, need to deploy your own (like wormhole), not recommended for small project)
  - [x] what is local mode (TODO: add more details): usually instant sealing and localmode to test contracts (especially ganache target hardhat scripts), and to test business logic and in a more production like env, use mandala
  - [x] how to debug failed tx, use the same hash to check subscan https://blockscout.acala.network/tx/0xec304c62a61c56680522c09a80c7280fe4d985038203df70435cc925a7fe877f/internal-transactions
  - [x] acala gas consts are different than mandala/karura

**Comment by ThunderDeliverer** [comment]
@shunjizhan could you change the unordered list to the task list? I think it will be easier to track what has already been done and what still needs to be done 🤔
