### ISSUE TITLE
eth_chainId is returning 0x0 

### ISSUE THREAD

**Issue by gluneau** [AcalaNetwork/bodhi.js#457]
eth_chainId is returning 0x0 so can't add Karura as a network in Metamask as reported by @timbrinded 

```
curl --location --request GET 'https://eth-rpc-karura.aca-api.network/' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "eth_chainId",
    "params": [],
    "id": 1
}'
```

@zjb0807 remove the chainId consts from evm module. Suggests to use evmAccounts instead of evm
`chainId: +this.provider.api.consts.evm.chainId.toString()`
change to:
`chainId: +this.provider.api.consts.evmAccounts.chainId.toString()`

**Comment by zjb0807** [comment]
It works after restarting the `eth-rpc-adapter`. 
We will add the feature of detecting runtime upgrade
