### ISSUE TITLE
run build error

### ISSUE THREAD

**Issue by orgdad** [AcalaNetwork/bodhi.js#462]
yarn run build back error info, Please help

Failed to minify the code from this file: 

        ./node_modules/@open-wc/webpack-import-meta-loader/webpack-import-meta-loader.js!./node_modules/babel-loader/lib??ref--7-oneOf-2!./node_modules/@acala-network/eth-providers/lib/base-provider.js:786

**Comment by shunjizhan** [comment]
can you try `rush build`? we use `rush` as package manager
