### ISSUE TITLE
subql only skip unsupported event

### ISSUE THREAD

**Issue by shunjizhan** [AcalaNetwork/bodhi.js#464]
https://github.com/AcalaNetwork/bodhi.js/blob/master/evm-subql/src/mappings/mappingHandlers.ts#L39
if error msg includes `unsupported event`, then return and skip. If not, it might be some real value, should throw it

**Comment by zjb0807** [comment]
https://github.com/AcalaNetwork/bodhi.js/blob/c824f483d7b80f164f3700a1c3df88e4d897c2de/evm-subql/src/mappings/mappingHandlers.ts#L23
throw error
