### ISSUE TITLE
implement `eth_getHistory`

### ISSUE THREAD

**Issue by gluneau** [AcalaNetwork/bodhi.js#467]
getHistory() returns a wallet's recent transactions.

 [getHistory ( addressOrName [ , startBlock [ , endBlock ] ] )](https://docs.ethers.io/v3/api-providers.html#provider-specific-extra-api-calls).

**Comment by ntduan** [comment]
This is not an eth specification, for eth chain, this is implemented by querying etherscan. For us, I think it can be implemented by querying graphql. 

Actually, it is possible now to query directly through graphql, which is also more flexible.

like this:

https://studio.apollographql.com/sandbox/explorer?endpoint=https%3A%2F%2Ftc7-graphql.aca-dev.network&explorerURLState=N4IgJg9gxgrgtgUwHYBcQC4QEcYIE4CeABAIq6EAUAJAGYCWANivukQCp4CGSAzp1CjoQkAJQRQEdAA4oAYo2Z4ANESoQ8YfACECrANodufAUNHjJMngHkN2ggEIAugEoiwADpIiRFF179BYTEJaRQeCnomFlVIxRV1TTwdVjVbJIJXDy9vIiQITR43TxycvM0ASTBikqI6KuySlAhqkpo8CDgWnKhhXwCAQTAwPAQeHi7vPv8TYXKkTQAPCaIGCABzHi1VjuW1zh4AVR4EepqiACNVqABrAAl9gAtlqeNApHueJ4acy%2BhrgDl4Od8MtYHAYAxOIIAG4IADi%2ByOJ2eBCkCGWPBQUJg42%2B3gQCzoKDE%2B2Ey1WGyKeNK%2BVGVLOJTKCEqyxKdVZPyuAKBIOpJV%2BNw%2BXwZOReAVMc0WHO8IzgEFhpxFRE4QxGY2lRDAUM4GqaUjoUFxSp8flepiFGopkoJHIAvst7d9Hd5HY6QEoQNDOHg6JxLqMMCAst53CBYiCMPScqGBdy4MC8KHWMGaqGGKMeGwHtwk0QAJwFgAcAHYAExKZahtYjKH4LM5yMFvOFgBsea6tor31D6lzemWKbOoaaucHDNDCBwnAYbGakdDAAYFgvS4WSy3CwAWTjFvMAVjzAGYW8Xi2BizQF8WW1AtwvN4fznnN1BgQuAIw0BA6kB2h1ds4xxKUM2h2SMgNTEBJxgadZ1zRdl1Xdctx3fcjxPM8LyvG87wfJ8XzfT9v1DP9qU7AcOVDHpUC4ARBmGDNRw1CcpxnOdWAQlc12vFDdwPY9T3PS9r1vTd70fZ9XwQD8vx-UizmdHJHGqcjsh7NIdHgkAtAAGSsABhABpAB9f4DgAWS0ABRERjIAESsgBlfSSKQW0QFtIA

**Comment by fisprak** [comment]
@ntduan Cool, thank you for sharing this info!

What rate limits does this GraphQL API has?
What options are there to avoid rate limiting?

**Comment by xlc** [comment]
The best way to ensure you are not rate limited is by hosting your own server. Alternately you can deploy the evm-subql project on the managed services at https://subquery.network/managedservices as well

**Comment by fisprak** [comment]
@xlc Thank you! By `emv-subql` you mean this: https://github.com/AcalaNetwork/bodhi.js/tree/46a70891a4728756f4af3d293814ee3395abbf59/evm-subql?

The difference between `evm-subql` and [`acala-subql`](https://github.com/AcalaNetwork/acala-subql/blob/master/docker-compose.yml#L31) is that `evm-subql` does the same plus runs Acala Mandala Testnet node?

**Comment by xlc** [comment]
Yes.

evm-subql is only about EVM related events. acala-subql is for everything.

the acala-evm-starter is a template that you meant to customize it with your contract ABI & related logic.

**Comment by fisprak** [comment]
@xlc Thank you :100:
