### ISSUE TITLE
Forward mode

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/bodhi.js#474]
Add new cli to enable forward mode that forwards Substrate RPCs to Substrate node.

Use `rpc_methods` to query all the supported RPC methods from Substrate node and only forward those.

Should be disabled by default.

**Comment by ntduan** [comment]
Does Forward need to support subscribe?

**Comment by jamesbayly** [comment]
I don't think it can support web socket subscriptions, but this is just intended for a short term fix

**Comment by xlc** [comment]
it should support subscription for ws connection. just also need to disconnect if the node side disconnected
