### ISSUE TITLE
Forward mode doesn't support subscribe

### ISSUE THREAD

**Issue by ianhe8x** [AcalaNetwork/bodhi.js#494]
> websocat 'wss://acala-mandala-adapter.api.onfinality.io/public-ws' --jsonrpc
> chain_subscribeNewHeads
> {"id":1,"jsonrpc":"2.0","result":"sGb6KkLMeg9Lc8q8"}

Only received the response of this rpc, but missed all following subscription messages.

**Comment by ntduan** [comment]
fixed by #502
