### ISSUE TITLE
return id is `null` when id is `0`

### ISSUE THREAD

**Issue by shunjizhan** [AcalaNetwork/bodhi.js#506]
![Screen Shot 2022-07-11 at 22 48 06](https://user-images.githubusercontent.com/16548786/178292089-96a01718-172b-4fbf-8e94-736db70fa70c.png)

**Comment by gluneau** [comment]
Same with `eth_call`, Seems that RPC node cannot handle with the "id":0 as a request parameter. 

![image](https://user-images.githubusercontent.com/2903505/178540040-c7a998b0-bdef-4326-85e9-e27735dc935a.png)
