### ISSUE TITLE
Dockerized local network only mines one block and then breaks

### ISSUE THREAD

**Issue by ThunderDeliverer** [AcalaNetwork/bodhi.js#517]
The latest addition to dockerized network `http://ghcr.io/acalanetwork/mandala-node:sha-0910ce3` results in the following error once the first block is mined:

````
evm-subql-mandala-node-1  | 2022-07-25 10:33:33.601 ERROR tokio-runtime-worker runtime: panicked at 'set_validation_data inherent needs to be present in every block!', /usr/local/cargo/git/checkouts/cumulus-c031d5994ef3f0e1/e5889f1/pallets/parachain-system/src/lib.rs:143:13   
evm-subql-mandala-node-1  | 2022-07-25 10:33:33.603 ERROR tokio-runtime-worker sc_consensus_manual_seal::rpc: Instant Seal encountered an error: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
````

Reverting back to `http://ghcr.io/acalanetwork/mandala-node:sha-2c8b71e` solves the issue.

I'm running this on `macOS Monterey (v 12.1)` with Apple M1 Max in Docker version `Docker Desktop 4.10.1 (82475)`.

**Comment by shunjizhan** [comment]
CI has been using  `0910ce31` and worked https://github.com/AcalaNetwork/bodhi.js/blob/master/docker-compose.yml#L97

could it be that this dockerized node isn't compatible with M1?

**Comment by shaunxw** [comment]
I tried latest master branch `e894cf` and it works well for me. Could you try this build instead?

**Comment by ThunderDeliverer** [comment]
I tried the latest master and it works as well 👌
