### ISSUE TITLE
Hardhat Tests Error Out

### ISSUE THREAD

**Issue by ferrell-code** [AcalaNetwork/bodhi.js#523]
I made a simple repo to demo unexpected failure in hardhat: https://github.com/ferrell-code/hardhat-revert-fails

I noticed failed null address passed to precompile fails. Also, passing an nonexistent enum value fails to, could be two unique issues

The problem may originate on the Acala node side due to evm rpc

Interestingly if you change ethers version to "5.6.1" you get different error message, could be a problem with ethers?

**Comment by ntduan** [comment]
await should be placed outside of expect, not inside. Like this: 
`await expect(instance.getDexRewardRate(NULL_ADDRESS)).to.be.reverted;`

**Comment by ferrell-code** [comment]
Thanks @ntduan!, should of known better than to trust the error message when debugging this

If there is way to make error message better that would be nice, but maybe due to various dependencies that is difficult
