### ISSUE TITLE
The test case failed after the dependency was updated

### ISSUE THREAD

**Issue by ntduan** [AcalaNetwork/bodhi.js#527]
https://github.com/AcalaNetwork/bodhi.js/pull/526
https://github.com/AcalaNetwork/bodhi.js/runs/7606998136?check_suite_focus=true

**Comment by shunjizhan** [comment]
what updates did it have? I tried to run `rush update` locally and it seems the lock file doesn't change

**Comment by ntduan** [comment]
> what updates did it have? I tried to run `rush update` locally and it seems the lock file doesn't change
You can try `rush update --full`

**Comment by shunjizhan** [comment]
I fixed the rpc adapter ones, for the schedule one, is it safe to just change to expectation? @zjb0807 
```
bodhijs-waffle-examples-test-1  |       AssertionError: expected '4999959678683168000000' to equal '4999959692449420000000'
bodhijs-waffle-examples-test-1  |       + expected - actual
bodhijs-waffle-examples-test-1  | 
bodhijs-waffle-examples-test-1  |       -4999959678683168000000
bodhijs-waffle-examples-test-1  |       +4999959692449420000000
bodhijs-waffle-examples-test-1  |       
bodhijs-waffle-examples-test-1  |       at Context.<anonymous> (test/Scheduler.test.ts:160:69)
bodhijs-waffle-examples-test-1  |       at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by shunjizhan** [comment]
not sure about the truffle failure, might need some digging, sometimes after upgrading ethers version it has some new behaviour that can break previous things
