### ISSUE TITLE
docker-compose up results in error for feed-tx service

### ISSUE THREAD

**Issue by ayudh37** [AcalaNetwork/bodhi.js#546]
I'm on a MAC with an M1 chip

<img width="1440" alt="Screenshot 2022-08-19 at 4 46 27 PM" src="https://user-images.githubusercontent.com/11541303/185581360-7fd47b42-4fa8-4b1e-b278-d6ee0d7656ae.png">

**Comment by zjb0807** [comment]
please build the base image first
`docker build . -t bodhi-base -f docker/bodhi-base.Dockerfile`

**Comment by zjb0807** [comment]
https://github.com/AcalaNetwork/bodhi.js/blob/2860f29e68f5f4b80564f9ce2bf8979a6a5cf7be/.github/workflows/test.yml#L31

**Comment by ayudh37** [comment]
should the README.md be updated?

**Comment by ayudh37** [comment]
btw after running `docker build . -t bodhi-base -f docker/bodhi-base.Dockerfile` and doing `docker-compose up`, I get this error
<img width="561" alt="Screenshot 2022-08-19 at 5 25 20 PM" src="https://user-images.githubusercontent.com/11541303/185588779-dfc65d53-7d60-4421-b0f3-448eb796833c.png">

**Comment by zjb0807** [comment]
```
docker logs -f 2195
```
please check the container logs

**Comment by ayudh37** [comment]
<img width="1440" alt="Screenshot 2022-08-19 at 5 30 50 PM" src="https://user-images.githubusercontent.com/11541303/185589753-539856c9-c852-48d0-8690-506206c104d7.png">

**Comment by zjb0807** [comment]
https://github.com/AcalaNetwork/bodhi.js/blob/2860f29e68f5f4b80564f9ce2bf8979a6a5cf7be/docker/eth-rpc-adapter-test.Dockerfile#L30

the default port is 9944. Did you change it to 9945?

**Comment by ayudh37** [comment]
yes so I reinstalled the repo and redid the installation above but still see this error now referencing mandala-node:9944 
<img width="827" alt="Screenshot 2022-08-19 at 6 26 38 PM" src="https://user-images.githubusercontent.com/11541303/185599802-4c4e07fa-fd17-4e35-9b42-feb4e4c8af16.png">
