### ISSUE TITLE
v2.5.2 does not respect WS_PORT env variable

### ISSUE THREAD

**Issue by mcf-rocks** [AcalaNetwork/bodhi.js#567]
eth-rpc-adapter v2.5.2 does not respect WS_PORT env variable, it ignores and uses 8545
```
version         : bodhi.js/eth-rpc-adapter/2.5.2
```
Version 2.5.0 also brok

But Version 2.4.21 works

```
Sep 29 11:40:41 m2 bash[1025415]:   version         : bodhi.js/eth-rpc-adapter/2.4.21
Sep 29 11:40:41 m2 bash[1025415]:   endpoint url    : ws://localhost:40520
Sep 29 11:40:41 m2 bash[1025415]:   subquery url    : http://localhost:4001
Sep 29 11:40:41 m2 bash[1025415]:   listening to    : http 40525 | ws 40526
```

**Comment by shunjizhan** [comment]
Hi, we recently had an updates to combine http and ws port, so there is no `WS_PORT` option anymore, instead it's `PORT`. Please check out here for all options https://github.com/AcalaNetwork/bodhi.js/tree/master/eth-rpc-adapter#options

**Comment by mcf-rocks** [comment]
ok, i actually did not realise you could use 1 port for both HTTP and WS.
