### ISSUE TITLE
Regression tests

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/bodhi.js#635]
Some regression tests to ensure the latest version still works with historical blocks to prevent bugs like https://github.com/AcalaNetwork/bodhi.js/pull/634

**Comment by shunjizhan** [comment]
I think we can deploy a dev version that index from the beginning whenever a version version is published. However, this can only test against our node, it won't catch older's nodes issue.

We can also encourage ppl to do database migration instead of full re-index

**Comment by xlc** [comment]
We don't always need to index whole thing to catch bugs. Just have a unit test that try to process few known edge case blocks should be enough.

**Comment by shunjizhan** [comment]
sounds great! That's what I plan for the next bodhi refactor, which will factor out a well tested util for subquery to use
