### ISSUE TITLE
Implement `eth_getTransactionByHash`

### ISSUE THREAD

**Issue by gluneau** [AcalaNetwork/bodhi.js#64]
This is a requirement to get the Aave test running.

https://github.com/AcalaNetwork/bodhi.js/blob/master/eth-rpc-adapter/src/eip1193-bridge.ts#L215

**Comment by shunjizhan** [comment]
duplicate #73

**Comment by shunjizhan** [comment]
ok no duplicate indeed lol

**Comment by ThunderDeliverer** [comment]
@shunjizhan could you prioritise this one, once you are done with the method you are currently working on? This is the call that currently blocks even the simplest examples.

**Comment by shunjizhan** [comment]
sure! I am pretty close to get this one done

**Comment by ThunderDeliverer** [comment]
Could you ping me once it(s included within the adapter? 😄

**Comment by shunjizhan** [comment]
yup! PR is currently under review #119

**Comment by shunjizhan** [comment]
closed with #119

**Comment by shunjizhan** [comment]
@ThunderDeliverer currently these is still something to improve, #120
