### ISSUE TITLE
we shouldn't be caching tx receipts in non-safe-mode

### ISSUE THREAD

**Issue by zjb0807** [AcalaNetwork/bodhi.js#657]
https://github.com/AcalaNetwork/bodhi.js/blob/80103cc49926c33e042b77fc6ec4d61f2d0d2a84/eth-providers/src/utils/BlockCache.ts#L3

If the transaction is on the forked block and does not exist on the longest chain, then our cache will give the wrong status.

Also need to confirm how subquery handles the fork problem

**Comment by shunjizhan** [comment]
subql only indexes finalized block, so it should be fine. 

For cache I guess we will first need to define the expected behaviors for `eth_getTransactionReceipt`:
- when a fork just happens and sibling block is not finalized
- when sibling block is already finalized

**Comment by shunjizhan** [comment]
actually I think we should still return the receipt in a fork, and it's up to the clients to check for finalization/fork. i.e. for ETH they need to wait for a couple confirmations, and for EVM+ they can use `eth_isBlockFinalized`

**Comment by shunjizhan** [comment]
@xlc @ntduan any insights on this?

**Comment by shunjizhan** [comment]
frontier returns `null` for non-canonical receipt though 
https://github.com/paritytech/frontier/pull/474/files

**Comment by xlc** [comment]
subql only cares about finalized blocks so eventually we will prune them.
I think it is not wrong to return receipt for tx in forks for some period of time. At least we have not yet received any requests about this so it should be ok.

**Comment by zjb0807** [comment]
> I think we should still return the receipt in a fork, since `eth_getTransactionReceipt` only cares if the tx is mined, without knowledge about it's finalization.

If a transaction is in a forked block, there are 3 situations:
1. Included in the longest chain and block of the same height
2. After replay, it is included in the last block of the longest chain
3. The node is doing evil, and the transaction is not included in the longest chain
If we have cached transaction receipts, we also need to maintain fork processing (delete or update). If not cached, it is up to the node to maintain the transaction state

> It's up to the clients/dapps to check for finalization/fork, if they ever care. For ETH they just for a couple confirmations, and for EVM+ they can use [eth_isBlockFinalized](https://evmdocs.acala.network/miscellaneous/faqs#how-to-check-if-a-transaction-is-finalized).

Dapp does not need to deal with forks, after confirming the height, verify that the transaction exists and the status is successful. 
Take wormhole and Ethereum as an example, after a few blocks, call eth_getTransactionReceipt to verify that the transaction status is successful. If we cached the transaction in `non-safe-mode`, and the transaction does not exist in the longest chain, then our cache status will return success.

**Comment by zjb0807** [comment]
ChatGPT told me the code is helpful for us
```
const { ApiPromise, WsProvider } = require('@polkadot/api');

async function subscribeToFinalizedBlock() {
  const wsProvider = new WsProvider('wss://rpc.polkadot.io');
  const api = await ApiPromise.create({ provider: wsProvider });

  api.derive.chain.subscribeNewHeads(async (header) => {
    const finalizedHeader = await api.derive.chain.getFinalizedHead();
    console.log(`Latest block: ${header.number}, Finalized block: ${finalizedHeader.number}`);
  });
}

subscribeToFinalizedBlock();
```

**Comment by shunjizhan** [comment]
Not sure if it's 100% correct but makes sense to me. I think the main idea is that a receipt alone can never guarantee the tx's status. 

![chatGPT-screenshot (2)](https://user-images.githubusercontent.com/16548786/218383720-5acf0d1a-50b8-47d4-9256-8fc7235111d8.png)

**Comment by shunjizhan** [comment]
For wormhole we provided a safe mode just for their convenience, but they should be able to check finalization without safe mode. Also most apps doesn't care about finalization, for example, when we send a tx in metamask, or make a swap in uniswap, they will mark the tx as complete as soon as we can get a receipt (1 confirmation). It won't wait 12 confirmations, or monitor for forks, since it doesn't care.

So it's up to the dapps to monitor for fork or finalization, **if they care**, such as wormhole.

**Comment by shunjizhan** [comment]
can you clarify what do you mean by "inaccurate"? If I didn't miss anything, I believe all info in receipts should be accurate, even if it's a stale receipt. 

But I agree there will be some inconsistency between cache and subql. Cache will strictly have more receipts than subql, which are unfinalized ones (remember we call cache as "unfinalizedCache" a ling time ago). But such inconsistency doesn't seem to be an issue, since as we mentioned above, receipt doesn't guarantee finalization, so it's normal if we find a receipt today (in cache), and can't find it tomorrow (in subql).

**Comment by shunjizhan** [comment]
> it's normal if we find a receipt today (from cache), and can't find it tomorrow (from subql).

However we can guarantee it only happens for **stale receipt**, for finalized receipt we will always be able to find them.

**Comment by shunjizhan** [comment]
> it's normal if we find a receipt today (from cache), and can't find it tomorrow (from subql).

@zjb0807  would this break blockscout? It's not "wrong behavior" but might cause issue for blockscout. I guess we can stick with current behavior for now, and if there is any issue (from blockscout or complained by other users), we can add a layer to cache that checks if receipt is stale before returning

**Comment by zjb0807** [comment]
> so it's fine if we find a receipt today (from cache), and can't find it tomorrow (from subql).

It's very bad for blockscout and exchange. 
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/16496415/218597308-a420e57a-0d7e-4d01-9b9c-6cc67c67d2ec.png">

People confirm the success of a transaction by checking the status and confirmation count of the receipt. If `eth_getTransactionReceipt` returns successfully within `maxCachedBlocks` blocks, but fails on the `maxCachedBlocks+1` block, it would be very bad.

> can you clarify what do you mean by "inaccurate"? If I didn't miss anything, I believe all info in receipts should be accurate, even if it's a stale receipt.

If a tx is in a forked block, there are 3 cases:

- Included in the longest chain and block of the same height, different block hash
- After a replay, it is included in a new block
- The node is doing evil, and the tx is not included in the longest chain(can't be replayed)

so block height、block hash、status are inaccurate.
