### ISSUE TITLE
package path error

### ISSUE THREAD

**Issue by zjb0807** [AcalaNetwork/bodhi.js#739]
https://github.com/AcalaNetwork/bodhi.js/blob/c36943174f79e436754171acd3c32e3b7d1c3044/packages/eth-providers/package.json#L45-L60

```
var _utils = require("@acala-network/eth-providers/lib/utils");
```

```
Error: Cannot find module 'node_modules/@acala-network/eth-providers/lib/lib/utils.js'
```

**Comment by ermalkaleci** [comment]
@zjb0807  how are you getting this? `@acala-network/eth-providers/lib/utils` doesn't exists on codebase. If you have this on some other project make sure to remove `/lib/`.
Should be `@acala-network/eth-providers/utils`

**Comment by zjb0807** [comment]
https://github.com/AcalaNetwork/acala.js/pull/486
