### ISSUE TITLE
listener count limitation

### ISSUE THREAD

**Issue by shunjizhan** [AcalaNetwork/bodhi.js#836]
currently we don't have any limitation for listeners, so when there are many users this might slow down or even crash RPC. Need to do some research about the best way to deal with this

**Comment by xlc** [comment]
or we can just setup subway

**Comment by shunjizhan** [comment]
yeah that's a great point! So bodhi will only have 1 subscriber, which is subway lol
Does subway already support eth RPCs?

**Comment by xlc** [comment]
Yeah it should work. Otherwise it will be a bug.

**Comment by shunjizhan** [comment]
awesome! Then I guess we can gradually try rollout subway deployment. It's not a priority since we don't seem to have that many request for now, but I guess it's always good to plan a little ahead

created a tentative subway deployment roadmap #839, let me know if you have any thoughts!

**Comment by shunjizhan** [comment]
this feature is not needed anymore then
